<a href="https://colab.research.google.com/github/ashishkumar30/Machine-Learning/blob/master/numpy_acadview.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
a = np.array([1,2,3])

In [0]:
type(a)

numpy.ndarray

In [0]:
a

array([1, 2, 3])

In [0]:
lst = [1,2,3]

In [0]:
type(lst)

list

In [0]:
a.shape

(3,)

In [0]:
a.reshape(3,1)

array([[1],
       [2],
       [3]])

In [0]:
a = np.array([4,5,6])

In [0]:
a[0]

4

In [0]:
a[1]

5

In [0]:
a = np.zeros((2,2),dtype = 'int64')

In [0]:
a

array([[0, 0],
       [0, 0]], dtype=int64)

In [0]:
a = np.ones((2,2))

In [0]:
a

array([[1., 1.],
       [1., 1.]])

In [0]:
a.dtype

dtype('float64')

In [0]:
a = np.ones((2,2),dtype = 'int64')

In [0]:
a

array([[1, 1],
       [1, 1]], dtype=int64)

In [0]:
a = np.full((2,2),100)

In [0]:
a

array([[100, 100],
       [100, 100]])

In [0]:
a = np.eye(2)

In [0]:
a

array([[1., 0.],
       [0., 1.]])

In [0]:
a = np.diag([1,2,3])

In [0]:
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [0]:
a.ndim #2-d array

2

In [0]:
a.shape #attribute not function

(3, 3)

In [0]:
a.size #total number of elements in the matrix

9

In [0]:
a.dtype #datatype

dtype('int32')

In [0]:
a = np.arange(15)

In [0]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
type(a)

numpy.ndarray

In [0]:
a = a.reshape((3,5))

In [0]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [0]:
a.shape

(3, 5)

In [0]:
a[0:2,0:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [0]:
a = np.array([[1,2],[3,4],[5,6]])

In [0]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a[[0,1,2],[0,1,0]]

array([1, 4, 5])

In [0]:
a[0,0]

1

In [0]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a>2

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [0]:
a[a>2]

array([3, 4, 5, 6])

In [0]:
x = np.array([[1,2],[3,4]])

In [0]:
y = np.array([[5,6],[7,8]])

In [0]:
x

array([[1, 2],
       [3, 4]])

In [0]:
y

array([[5, 6],
       [7, 8]])

In [0]:
np.add(x,y) #element wise addition

array([[ 6,  8],
       [10, 12]])

In [0]:
x+y

array([[ 6,  8],
       [10, 12]])

In [0]:
np.subtract(x,y) #similarly multiply and divide

array([[-4, -4],
       [-4, -4]])

In [0]:
x-y

array([[-4, -4],
       [-4, -4]])

In [0]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [0]:
v = np.array([9,10])

In [0]:
v

array([ 9, 10])

In [0]:
w = np.array([11,12])

In [0]:
w

array([11, 12])

In [0]:
v.dot(w)

219

In [0]:
y

array([[5, 6],
       [7, 8]])

In [0]:
y.T

array([[5, 7],
       [6, 8]])

In [0]:
y

array([[5, 6],
       [7, 8]])

In [0]:
y.sum(axis=0) #column

array([12, 14])

In [0]:
y.sum(axis=1) #row

array([11, 15])

In [0]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
np.mean(a) 

3.5